spring:
  application:
    name: java-scaffold
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF8&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=true&requireSSL=true
    username: root
    password: 1qaz2wsx
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
logging:
  level:
    root: info
server:
  servlet:
    context-path: /api

